baseURL = 'https://nanumlearn.enochyu.com/'
locale = 'en-us'
title = 'Nanum Learn'

enableRobotsTXT = true

[params]
author = "Enoch Yu"
favicon = "/img/favicon/favicon.ico"
  [params.social]
    youtube = "https://www.youtube.com/@enochyu_official"
    discord = "https://discord.gg/6ABSqUf63"
    github = "https://github.com/enochyu-official"

[security]
  allowContent = ['^text/html$', '^text/markdown$']


